apiVersion: v1
kind: Service
metadata:
  name: {{ include "accesschart.fullname" . }}
  labels:
    {{- include "accesschart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ssh-exporter
      port: {{ .Values.service.port "port"}}
      targetPort: {{ .Values.service.port "targetPort"}}
      nodePort: {{ .Values.service.port "nodePort"}}
  selector:
    {{- include "accesschart.selectorLabels" . | nindent 4 }}
